
// Allow GitHub image rendering
:imagesdir: ../images

== NFS

If you’re using a test _VM_ for the _NFS_ server, and assuming you're planning to use _NFS_ for the shared storage, make sure the _nfs_ service is installed, configured and activated on the _NFS Server_.

We need to prepare the shared devices with the appropriate information and test it before create the cluster.

Create the shared folders:

[source, bash]
----
[root@nfssrv01 ~]# mkdir -p /opt/opennms/etc
[root@nfssrv01 ~]# mkdir -p /opt/opennms/share
[root@nfssrv01 ~]# mkdir -p /opt/opennms/pgpool
----

Add the following content to the `/etc/exports` file:

[source, bash]
----
/opt/opennms/etc      192.168.205.0/24(rw,sync,no_root_squash)
/opt/opennms/share    192.168.205.0/24(rw,sync,no_root_squash)
/opt/opennms/pgpool   192.168.205.0/24(rw,sync,no_root_squash)
----

The above content is based on the _Vagrant lab_.
On a real deployment, the networks must be different.
The above network paths must be accessible from the _OpenNMS_ servers.

As mentioned before, the _postgres_ user must exist on the _NFS_ server:

[source, bash]
----
[root@nfssrv01 ~]# mkdir /var/lib/pgsql
[root@nfssrv01 ~]# groupadd -r -g 26 postgres
[root@nfssrv01 ~]# useradd -r -u 26 -M -d /var/lib/pgsql -n -g postgres postgres
[root@nfssrv01 ~]# chown postgres:postgres /var/lib/pgsql/
----

Also, be sure that the domain for your deployment (in this case `local`) is declared in `/etc/idmapd.conf` on the _NFS_ server and all _NFS_ clients.
In some cases, it might be required to restart the _NFS_ services on the _NFS_ server, and clear the _idmap_ cache on the clients with `nfsidmap -c`.

After modifying `/etc/exports`, restart the nfs service:

On _RHEL/CentOS 6_:

[source, bash]
----
[root@nfssrv01 ~]# service nfs restart
----

On _RHEL/CentOS 7_:

[source, bash]
----
[root@nfssrv01 ~]# systemctl restart rpcbind nfs-server
----

Make sure that the local copy of `/opt/opennms/etc`, `/var/opennms` and `/etc/pgpool-II-96/` created and configured on `onmssrv01` are synchronized with the _NFS_ server:

[source, bash]
----
[root@onmssrv01 ~]# rsync -avr --delete /opt/opennms/etc/ nfssrv01:/opt/opennms/etc/
[root@onmssrv01 ~]# rsync -avr --delete /var/opennms/ nfssrv01:/opt/opennms/share/
[root@onmssrv01 ~]# rsync -avr --delete /etc/pgpool-II-96/ nfssrv01:/opt/opennms/pgpool/
----

If you cannot perform the synchronization, check the credentials and the target mount point with the administrators of the _NFS_ server.

Remove all the content from the directories that will be mounted through _NFS_:

[source, bash]
----
[root@onmssrv01 ~]# rm -rf /opt/opennms/etc/*
[root@onmssrv01 ~]# rm -rf /opt/opennms/etc/.git*
[root@onmssrv01 ~]# rm -rf /var/opennms/*
[root@onmssrv01 ~]# rm -rf /etc/pgpool-II-96/*

[root@onmssrv02 ~]# rm -rf /opt/opennms/etc/*
[root@onmssrv02 ~]# rm -rf /var/opennms/*
[root@onmssrv02 ~]# rm -rf /etc/pgpool-II-96/*
----

Make sure that the `nfs-utils` package is installed on the _OpenNMS_ servers:

[source, bash]
----
[root@onmssrv01 ~]# yum install nfs-utils -y
[root@onmssrv02 ~]# yum install nfs-utils -y
----

Mount the filesystems on each server to make sure that works.

[source, bash]
----
[root@onmssrv01 ~]# mount -t nfs -o vers=4 nfssrv01:/opt/opennms/etc/ /opt/opennms/etc/
[root@onmssrv01 ~]# mount -t nfs -o vers=4 nfssrv01:/opt/opennms/share/ /var/opennms/
[root@onmssrv01 ~]# mount -t nfs -o vers=4 nfssrv01:/opt/opennms/pgpool/ /etc/pgpool-II-96/

[root@onmssrv02 ~]# mount -t nfs -o vers=4 nfssrv01:/opt/opennms/etc/ /opt/opennms/etc/
[root@onmssrv02 ~]# mount -t nfs -o vers=4 nfssrv01:/opt/opennms/share/ /var/opennms/
[root@onmssrv02 ~]# mount -t nfs -o vers=4 nfssrv01:/opt/opennms/pgpool/ /etc/pgpool-II-96/
----

IMPORTANT: Make sure that the permissions on `/etc/pgpool-II-96/` are correct.
           If they are not correct (i.e. like showing nobody instead of _postgres_ as the owner of the files), validate with the _NFS_ administrators why it is not working.
           Besides the _nobody_ user, you should see the following message on `/var/log/messages`:

[source, bash]
----
Jul 16 17:48:04 onmssrv01 nfsidmap[5353]: nss_getpwnam: name 'nobody' does not map into domain 'local'
----

As a workaround, do not use the cluster resource associated with `/etc/pgpool-II-96/`, and synchronize this directory back to each _OpenNMS_ server, and fix the permissions.

Now, unmount the filesystem on each server, as they will be managed by the cluster.

[source, bash]
----
[root@onmssrv01 ~]# umount /opt/opennms/etc/
[root@onmssrv01 ~]# umount /var/opennms/
[root@onmssrv01 ~]# umount /etc/pgpool-II-96/

[root@onmssrv02 ~]# umount /opt/opennms/etc/
[root@onmssrv02 ~]# umount /var/opennms/
[root@onmssrv02 ~]# umount /etc/pgpool-II-96/
----

IMPORTANT: Do not declare the external filesystems on `/etc/fstab`, the mount/umount operation of the shared filesystems will be managed through the cluster services, not the operating system.
